### ISSUE TITLE
Does not check if object is within printable area when modifying object settings

### ISSUE THREAD

**Issue by NikWillOrStuff** [prusa3d/PrusaControl#22]
version 0.9.2_297_beta, on windows

if you import an object, then move/scale it outside of the printable area using the "Object settings" menu, then avoid moving your mouse inside the 3D preview area when you click the "Generate" button, it will start generating gcode while simultaneously giving you the "Object blah... is out of printable area!" error.

compared to the normal behavior, moving the object outside of the print area by dragging the object in the 3D view, it will instantly give you the error message, and make the "Generate" button unclickable.

this isn't an important issue, as the error message is still there in the gcode preview menu, and it makes the "Save G-Code" button unclickable.

**Comment by prusa3d-bb** [comment]
Hello, 

thank you for feedback I will pass it to Prusacontrol developers, I tried to replicate it and I understand what you mean, but it does not really seem to be an important issue as it is doing what it should - preventing user from printing something out of bounds. 

Best regards,


Honza Vysušil
Customer Support


PRUSA Research
+420 222 263 718
+421 220 570 305
Partyzánská 188/7a, 17000, Prague
shop.prusa3D.com

--- original message ---
On Sun, Jul 2, 2017 at 08:56 pm, <notifications@github.com> NikWillOrStuff wrote:


version 0.9.2_297_beta, on windows

if you import an object, then move/scale it outside of the printable area using the "Object settings" menu, then avoid moving your mouse inside the 3D preview area when you click the "Generate" button, it will start generating gcode while simultaneously giving you the "Object blah... is out of printable area!" error.

compared to the normal behavior, moving the object outside of the print area by dragging the object in the 3D view, it will instantly give you the error message, and make the "Generate" button unclickable.

this isn't an important issue, as the error message is still there in the gcode preview menu, and it makes the "Save G-Code" button unclickable.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by tibor-vavra** [comment]
Solved by commit 4e18eb4bc739cac5c176202eb24a2487cd519acb
