### ISSUE TITLE
Feature request: duplicate object 

### ISSUE THREAD

**Issue by CpHarding** [prusa3d/PrusaControl#59]
It would be good to have the ability to put 30 of a small object on the plate without needing to paste 30 times.

Having a "duplicate" button which asks how many copies you want would be useful, and the ability to manage how many duplicates,

**Comment by prusa3d-bb** [comment]
Hello,
Thank you very much for this opinion, we will forward it to proper department.
Kind regards


—

Lukáš Vacek

Customer Support

PRUSA Research
+420 222 263 718
+421 220 570 305
188/7A Partyzánská, 17000Prague 7 - Holešovice
shop.prusa3D.com

--- original message ---
On Fri, Nov 24, 2017 at 11:55 am, <notifications@github.com> CpHarding wrote:


It would be good to have the ability to put 30 of a small object on the plate without needing to paste 30 times.

Having a "duplicate" button which asks how many copies you want would be useful, and the ability to manage how many duplicates,

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
