### ISSUE TITLE
How can we change filament details?

### ISSUE THREAD

**Issue by iandouglas** [prusa3d/PrusaControl#84]
The application is bundled (at least the Mac version) with `/Applications/PrusaControl.app/Contents/Resources/data` folder where there are files like `materials_i3_mk3.json` that is a large JSON blob of filament settings (temperature, retraction, speeds, etc). These filament settings also seem to get copied into our home folder under `~/Library/Application Support/PrusaControl/data`

However, modifying those filament settings JSON files don't seem to have any effect on PrusaControl's choices. For example, there's a `sort` attribute in the JSON blob which, you'd think, would tell the software how to order things in the software, but changing those values had no effect. Adding new filaments had no effect. Changing names of filaments had no effect. I've tried making changes in both the `/Applications/PrusaControl.app/` JSON files and the home folder `~/Library/.../PrusaControl` JSON files.

I really like the simplicity of PrusaControl, but I'd like to have filaments to pick from like "Generic PLA 200C" or "Generic PLA 205C" for different temperatures, or adding new filaments with settings I like without having to go into the full Slic3r Prusa Edition and fuss with all of the other settings screens etc just to tweak a temperature or speed or retraction or extrusion multiplier if I could just modify these JSON files.

**Comment by prusa3d-bb** [comment]
Hello,
Thank you for your feedback. Everything will be forwarded to our colleagues from IT department!
Hope you have a great day.
Kind regards


—
Lukáš Vacek
Customer Support


PRUSA Research
+420 222 263 718
+421 220 570 305
188/7a Partyzánská, 17000, Prague
shop.prusa3D.com


For simple troubleshooting, please use: http://help.prusa3d.com


Please rate our reply ...be generous :-)

--- original message ---
On Wed, Mar 21, 2018 at 07:40 pm, <notifications@github.com> ian douglas wrote:


The application is bundled (at least the Mac version) with /Applications/PrusaControl.app/Contents/Resources/data folder where there are files like materials_i3_mk3.json that is a large JSON blob of filament settings (temperature, retraction, speeds, etc). These filament settings also seem to get copied into our home folder under ~/Library/Application Support/PrusaControl/data

However, modifying those filament settings JSON files don't seem to have any effect on PrusaControl's choices. For example, there's a sort attribute in the JSON blob which, you'd think, would tell the software how to order things in the software, but changing those values had no effect. Adding new filaments had no effect. Changing names of filaments had no effect. I've tried making changes in both the /Applications/PrusaControl.app/ JSON files and the home folder ~/Library/.../PrusaControl JSON files.

I really like the simplicity of PrusaControl, but I'd like to have filaments to pick from like "Generic PLA 200C" or "Generic PLA 205C" for different temperatures, or adding new filaments with settings I like without having to go into the full Slic3r Prusa Edition and fuss with all of the other settings screens etc just to tweak a temperature or speed or retraction or extrusion multiplier if I could just modify these JSON files.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by 0ctane** [comment]
I too would like to know how to add/remove/view the filament settings.

**Comment by iandouglas** [comment]
@0ctane If you're on a Mac, try editing the files under `~/Library/Application Support/PrusaControl/data/` ... I had originally edited those files but no change was made, but I uninstalled the app, reinstalled the app, edited the files, and now it's working.

<img width="159" alt="screen shot 2018-03-21 at 8 26 27 pm" src="https://user-images.githubusercontent.com/168030/37747738-2eb26a5c-2d46-11e8-9c5b-6e4a077f0582.png">
